#!/bin/sh
# To test whether scaling is stable over long periods of time, i.e. does not
# destabilise firing and force network into epilepsy / silence.
# Run for various values of activitygamma (scaling 'integral controller' weight)


# Set save path
datadir="/home/archive/users/rowanms-data/stdpscaling/onlyscaling"

# Set name of parameter to vary
var="activitygamma"

# Set list of values to try
vals="1e-7 1e-8 1e-9 1e-10 1e-11 1e-12 1e-13 1e-14 1e-15"

# Set non-varying parameters with '-c' prefix
# e.g. args="-c {activitybeta=10e-7} -c {activitytau=100e3}"

# Turn on scaling after 1000s
# Run for 160000 s (~44hrs) of sim time
args="-c {stdpsim=1} -c {scaling=1} -c {PreDur=160000} -c {PostDur=0} -c {LearnDur=0}"

./batchcommon $datadir $var "$vals" "$args"
