#!/bin/sh
# Training with STDP whilst synaptic scaling is switched on, for various
# STDP increment rates, to see if scaling balances out the epileptiform behaviour
# and can prevent it from happening

# Set save path
datadir="/home/archive/users/rowanms-data/stdpscaling/trainingandscaling"

# Set name of parameter to vary
var="plastEEinc"

# Set list of values to try
vals="0.0001 0.0005 0.001 0.005 0.01 0.05"

# Set non-varying parameters with '-c' prefix
# e.g. args="-c {activitybeta=10e-7} -c {activitytau=100e3}"
args="-c {stdpsim=1} -c {scaling=1}"

./batchcommon $datadir $var "$vals" "$args"
