#!/bin/sh
# The main point of all these experiments -- check training with STDP whilst
# synaptic scaling is switched on, for various training signal frequencies,
# to see if scaling balances out the epileptiform behaviour at high-freq training

# Set save path
datadir="/home/archive/users/rowanms-data/stdpscaling/trainingandscaling"

# Set name of parameter to vary
var="TrainRate"

# Set list of values to try
vals="2 4 6 8 10 12 14 16"

# Set non-varying parameters with '-c' prefix
# e.g. args="-c {activitybeta=10e-7} -c {activitytau=100e3}"
args="-c {stdpsim=1} -c {scaling=1}"

./batchcommon $datadir $var "$vals" "$args"
